<?xml version="1.0"?>
<!--Differential Drive Robot Definition-->
<!--Author: Sreejith S-->
<!--Date: Fri 15 May 2020 17:26:48 UTC-->

<robot name="diff_drive_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--Materials-->
    <xacro:include filename="$(find custom_bot)/urdf/materials.xacro"/>
    <xacro:include filename="$(find custom_bot)/urdf/gazebo.xacro"/>
    <!--Properties-->
    <xacro:property name="wheel_radius" value="0.032"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="laser_radius" value="0.025"/>
    <xacro:property name="laser_height" value="0.025"/>
    <xacro:property name="camera_dim" value="0.02 0.03 0.02"/>
    <xacro:property name="pi_rads" value="3.14159"/>
    <!--Macros-->
    <xacro:macro name="cylinder_inertia" params="mass r l">
        <inertia ixx="${mass*(3*r*r+l*l)/12}" ixy="0" ixz="0"
            iyy="${mass*(3*r*r+l*l)/12}" iyz="0.0"
            izz="${mass*(r*r)/2}"/>
    </xacro:macro>

  <link name="base_footprint">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </visual>
  </link>

    <link name="base_link">
        <visual>
            <origin rpy="1.57079632679 0 1.57079632679 " xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://custom_bot/meshes/Robot_chassis.STL" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="red"/>
        </visual>
        <inertial>
            <origin rpy="1.57079632679 0 1.57079632679 " xyz="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="0.015" ixy="0" ixz="0" iyy="0.0375" iyz="0" izz="0.0375"/>
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 -0.027"/>
            <geometry>
                <box size="0.15 .20 .045"/>
            </geometry>
        </collision>
    </link>

    <link name="front_castor_of_wheel">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 -0.009375"/>
            <geometry>
                <cylinder radius="0.00625" length="0.01875"/>
            </geometry>
            <material name="white"/>
        </visual>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 -0.009375"/>
            <mass value="1"/>
            <inertia ixx="0.00083" ixy="0" ixz="0" iyy="0.00083" iyz="0" izz="0.000167"/>
        </inertial>
         <collision>
            <origin rpy="0 0 0" xyz="0 0 -0.009375"/>
            <geometry>
                <cylinder radius="0.00625" length="0.01875"/>
            </geometry>
        </collision>
    </link>

    <link name="front_wheel">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="0.00625"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <inertial>
            <mass value="1"/>
            <inertia ixx="5.1458e-5" ixy="0" ixz="0" iyy="5.1458e-5" iyz="0.0" izz="6.125e-5"/>
        </inertial>
        <collision>
            <geometry>
                <sphere radius="0.00625"/>
            </geometry>
        </collision>
    </link>

    <link name="right_wheel">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <!--<cylinder radius="0.035" length="0.05"/>-->
                <mesh filename="package://custom_bot/meshes/wheel.STL" scale="1 1 1"/>
            </geometry>
            <material name="green"/>
        </visual>
        <inertial>
            <mass value="1"/>
            <inertia ixx="5.1458e-5" ixy="0" ixz="0" iyy="5.1458e-5" iyz="0.0" izz="6.125e-5"/>
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.0125"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
    </link>

    <link name="left_wheel">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://custom_bot/meshes/wheel.STL" scale="1 1 1"/>
                <!--<cylinder radius="0.035" length="0.05"/>-->
            </geometry>
            <material name="green"/>
        </visual>
        <inertial>
            <mass value="1"/>
            <inertia ixx="5.1458e-5" ixy="0" ixz="0" iyy="5.1458e-5" iyz="0.0" izz="6.125e-5"/>
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.0125"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
    </link>

    <link name="sensor_laser">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <inertial>
            <mass value="1"/>
            <xacro:cylinder_inertia mass="1" r="${laser_radius}" l="${laser_height}"/>
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.0125"/>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
        </collision>
    </link>

    <link name="sensor_camera">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${camera_dim}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <inertial>
            <mass value="1"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.0125"/>
            <geometry>
                <box size="${camera_dim}"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_foorprint_to_base_link" type="fixed">
        <origin xyz="0 0 0.0512"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <joint name="base_to_castor_socket" type="fixed">
        <origin xyz="-0.05 0 -0.025"/>
        <parent link="base_link"/>
        <child link="front_castor_of_wheel"/>
    </joint>

    <joint name="castor_socket_to_front_wheel" type="fixed">
        <origin xyz="0 0 -0.01875"/>
        <parent link="front_castor_of_wheel"/>
        <child link="front_wheel"/>
    </joint>

    <joint name="base_link_to_right_wheel" type="continuous">
        <origin rpy="-1.57079632679 0  0 " xyz="0.0267 -0.13 -0.02"/>
        <axis xyz="0 0 1 "/>
        <parent link="base_link"/>
        <child link="right_wheel"/>
    </joint>

    <joint name="base_link_to_left_wheel" type="continuous">
        <origin rpy="1.57079632679 0  0 " xyz="0.0267 0.13 -0.02"/>
        <axis xyz="0 0 -1 "/>
        <parent link="base_link"/>
        <child link="left_wheel"/>
    </joint>

    <joint name="base_link_to_laser" type="fixed">
        <origin rpy="0 0  0 " xyz="0.0 0.0 ${laser_height/2}"/>
        <axis xyz="0 0 0 "/>
        <parent link="base_link"/>
        <child link="sensor_laser"/>
    </joint>

    <joint name="base_link_to_camera" type="fixed">
        <origin rpy="0 0 ${pi_rads}" xyz="0.08 0.0 0.0"/>
        <axis xyz="0 0 0 "/>
        <parent link="base_link"/>
        <child link="sensor_camera"/>
    </joint>

</robot>
